apiVersion: v2
name: infra-charts
description: "Kubernetes Infrastructure Helm Chart"
type: application
version: 1.0.2
dependencies:
  # - name: longhorn
  #   version: "1.8.0"
  #   repository: "https://charts.longhorn.io"
  - name: kube-prometheus-stack
    version: "45.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: loki
    version: "2.5.0"
    repository: "https://grafana.github.io/helm-charts"
  # - name: cert-manager
  #   version: "1.11.0"
  #   repository: "https://charts.jetstack.io"
  # - name: ingress-nginx
  #   version: "4.0.0"
  #   repository: "https://kubernetes.github.io/ingress-nginx"
  # - name: external-dns
  #   version: "6.9.0"
  #   repository: "https://kubernetes-sigs.github.io/external-dns/"
  # - name: kyverno
  #   version: "1.10.0"
  #   repository: "https://kyverno.github.io/kyverno/"
  # - name: sealed-secrets
  #   version: "1.10.0"
  #   repository: "https://bitnami.com/sealed-secrets"
